
---
os_type: zlinux
#os_type: zos

# Name prefix for the created objects (VPC, subnetwork, VSI)
name_prefix: "{{ os_type }}-ansible"

# - VSI name for the instance
# - Profile name for the VSI
# - Regular expression for the VSI image name
#    Note: If multiple matches are found the first one is taken
instance-zlinux:
  name: "{{ name_prefix }}-zlinux-vsi"
  profile: bz2-2x8
  image: .*ubuntu-18-04.*s390x.*
instance-zos:
  name: "{{ name_prefix }}-zos-vsi"
  profile: mz2-2x16
  image: .*zos.*
  username: IBMUSER
  python_interpreters:
  - /usr/lpp/IBM/cyp/v3r9/pyz/bin/python3
  - /usr/lpp/IBM/cyp/v3r8/pyz/bin/python3
instance: "{{ lookup('vars','instance-' + os_type) }}"

# Name of the uploaded key
# Please notice that the same key might not be uploaded twice
# under different names
ssh_key_name: "{{ ansible_user_id | lower }}"
ssh_public_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"

# Size of the created subnetwork
total_ipv4_address_count: 256

# Region to deploy to
region: "jp-tok"
#region: "eu-gb"
#region: "br-sao"

#Zone within the region
zone: "{{region}}-1"

# If cache_vsi=True then VSI creation will only be attempted if not cached
#cache_vsi: True
cache_vsi: False

# The resource group to be used under the IBM Cloud Account
# resource_group_name: "{{ name_prefix }}-resources"